name: extensions_pack
description: Collection of dart extensions.

version: 2.4.1

repository: https://github.com/jorgelrj/extensions_pack

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  collection: ^1.18.0
  flutter: { sdk: flutter }
  intl: ^0.19.0
  recase: ^4.1.0
  url_launcher: ^6.3.1
