name: dart_http_client
description: HTTP client for Flutter
version: 0.0.2
homepage:

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.4.3+1
  flutter: { sdk: flutter }
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test: { sdk: flutter }
  json_serializable: ^6.7.1

flutter:
